title: 2026 Worldbuilding Project
email: fantomx11@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I thought I would spend 2026 creating a new world, but only a little bit each day. The idea is to write around 500 characters each day, adding a new element to the world with each article. I will use this article to organize the entries. Because of the nature of this project, some information may not be in conflict with later information, if this happens I will try to go back at some point and reconcile, but otherwise, assume that later articles overrule earlier articles
baseurl: "/2026-worldbuild"
defaults:
  -
    values:
      layout: "default"